
package precogasolina;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PrecoGasolina", targetNamespace = "http://precoGasolina/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PrecoGasolina {


    /**
     * 
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterPrecoGasolina", targetNamespace = "http://precoGasolina/", className = "precogasolina.ObterPrecoGasolina")
    @ResponseWrapper(localName = "obterPrecoGasolinaResponse", targetNamespace = "http://precoGasolina/", className = "precogasolina.ObterPrecoGasolinaResponse")
    @Action(input = "http://precoGasolina/PrecoGasolina/obterPrecoGasolinaRequest", output = "http://precoGasolina/PrecoGasolina/obterPrecoGasolinaResponse")
    public double obterPrecoGasolina();

}
