
package precogasolina;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PrecoGasolinaService", targetNamespace = "http://precoGasolina/", wsdlLocation = "http://localhost:8082/precoGasolina?wsdl")
public class PrecoGasolinaService
    extends Service
{

    private final static URL PRECOGASOLINASERVICE_WSDL_LOCATION;
    private final static WebServiceException PRECOGASOLINASERVICE_EXCEPTION;
    private final static QName PRECOGASOLINASERVICE_QNAME = new QName("http://precoGasolina/", "PrecoGasolinaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/precoGasolina?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRECOGASOLINASERVICE_WSDL_LOCATION = url;
        PRECOGASOLINASERVICE_EXCEPTION = e;
    }

    public PrecoGasolinaService() {
        super(__getWsdlLocation(), PRECOGASOLINASERVICE_QNAME);
    }

    public PrecoGasolinaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRECOGASOLINASERVICE_QNAME, features);
    }

    public PrecoGasolinaService(URL wsdlLocation) {
        super(wsdlLocation, PRECOGASOLINASERVICE_QNAME);
    }

    public PrecoGasolinaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRECOGASOLINASERVICE_QNAME, features);
    }

    public PrecoGasolinaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PrecoGasolinaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PrecoGasolina
     */
    @WebEndpoint(name = "PrecoGasolinaPort")
    public PrecoGasolina getPrecoGasolinaPort() {
        return super.getPort(new QName("http://precoGasolina/", "PrecoGasolinaPort"), PrecoGasolina.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PrecoGasolina
     */
    @WebEndpoint(name = "PrecoGasolinaPort")
    public PrecoGasolina getPrecoGasolinaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://precoGasolina/", "PrecoGasolinaPort"), PrecoGasolina.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRECOGASOLINASERVICE_EXCEPTION!= null) {
            throw PRECOGASOLINASERVICE_EXCEPTION;
        }
        return PRECOGASOLINASERVICE_WSDL_LOCATION;
    }

}
