
package cotacao;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Cotacao", targetNamespace = "http://cotacao/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Cotacao {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verificarCotacao", targetNamespace = "http://cotacao/", className = "cotacao.VerificarCotacao")
    @ResponseWrapper(localName = "verificarCotacaoResponse", targetNamespace = "http://cotacao/", className = "cotacao.VerificarCotacaoResponse")
    @Action(input = "http://cotacao/Cotacao/verificarCotacaoRequest", output = "http://cotacao/Cotacao/verificarCotacaoResponse")
    public double verificarCotacao(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
