
package calculardistancia;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculadorDistancia", targetNamespace = "http://calcularDistancia/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculadorDistancia {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calcularDistancia", targetNamespace = "http://calcularDistancia/", className = "calculardistancia.CalcularDistancia")
    @ResponseWrapper(localName = "calcularDistanciaResponse", targetNamespace = "http://calcularDistancia/", className = "calculardistancia.CalcularDistanciaResponse")
    @Action(input = "http://calcularDistancia/CalculadorDistancia/calcularDistanciaRequest", output = "http://calcularDistancia/CalculadorDistancia/calcularDistanciaResponse")
    public double calcularDistancia(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
