
package calculardistancia;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculadorDistanciaService", targetNamespace = "http://calcularDistancia/", wsdlLocation = "http://localhost:8081/calculadorDistancia?wsdl")
public class CalculadorDistanciaService
    extends Service
{

    private final static URL CALCULADORDISTANCIASERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULADORDISTANCIASERVICE_EXCEPTION;
    private final static QName CALCULADORDISTANCIASERVICE_QNAME = new QName("http://calcularDistancia/", "CalculadorDistanciaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/calculadorDistancia?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULADORDISTANCIASERVICE_WSDL_LOCATION = url;
        CALCULADORDISTANCIASERVICE_EXCEPTION = e;
    }

    public CalculadorDistanciaService() {
        super(__getWsdlLocation(), CALCULADORDISTANCIASERVICE_QNAME);
    }

    public CalculadorDistanciaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULADORDISTANCIASERVICE_QNAME, features);
    }

    public CalculadorDistanciaService(URL wsdlLocation) {
        super(wsdlLocation, CALCULADORDISTANCIASERVICE_QNAME);
    }

    public CalculadorDistanciaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULADORDISTANCIASERVICE_QNAME, features);
    }

    public CalculadorDistanciaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculadorDistanciaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculadorDistancia
     */
    @WebEndpoint(name = "CalculadorDistanciaPort")
    public CalculadorDistancia getCalculadorDistanciaPort() {
        return super.getPort(new QName("http://calcularDistancia/", "CalculadorDistanciaPort"), CalculadorDistancia.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculadorDistancia
     */
    @WebEndpoint(name = "CalculadorDistanciaPort")
    public CalculadorDistancia getCalculadorDistanciaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://calcularDistancia/", "CalculadorDistanciaPort"), CalculadorDistancia.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULADORDISTANCIASERVICE_EXCEPTION!= null) {
            throw CALCULADORDISTANCIASERVICE_EXCEPTION;
        }
        return CALCULADORDISTANCIASERVICE_WSDL_LOCATION;
    }

}
