
package validarcpfecnpj;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ValidadorService", targetNamespace = "http://validarCPFeCNPJ/", wsdlLocation = "http://localhost:8083/validador?wsdl")
public class ValidadorService
    extends Service
{

    private final static URL VALIDADORSERVICE_WSDL_LOCATION;
    private final static WebServiceException VALIDADORSERVICE_EXCEPTION;
    private final static QName VALIDADORSERVICE_QNAME = new QName("http://validarCPFeCNPJ/", "ValidadorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8083/validador?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VALIDADORSERVICE_WSDL_LOCATION = url;
        VALIDADORSERVICE_EXCEPTION = e;
    }

    public ValidadorService() {
        super(__getWsdlLocation(), VALIDADORSERVICE_QNAME);
    }

    public ValidadorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VALIDADORSERVICE_QNAME, features);
    }

    public ValidadorService(URL wsdlLocation) {
        super(wsdlLocation, VALIDADORSERVICE_QNAME);
    }

    public ValidadorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VALIDADORSERVICE_QNAME, features);
    }

    public ValidadorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidadorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Validador
     */
    @WebEndpoint(name = "ValidadorPort")
    public Validador getValidadorPort() {
        return super.getPort(new QName("http://validarCPFeCNPJ/", "ValidadorPort"), Validador.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Validador
     */
    @WebEndpoint(name = "ValidadorPort")
    public Validador getValidadorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://validarCPFeCNPJ/", "ValidadorPort"), Validador.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VALIDADORSERVICE_EXCEPTION!= null) {
            throw VALIDADORSERVICE_EXCEPTION;
        }
        return VALIDADORSERVICE_WSDL_LOCATION;
    }

}
