
package validarcpfecnpj;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Validador", targetNamespace = "http://validarCPFeCNPJ/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Validador {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validarCPFeCNPJ", targetNamespace = "http://validarCPFeCNPJ/", className = "validarcpfecnpj.ValidarCPFeCNPJ")
    @ResponseWrapper(localName = "validarCPFeCNPJResponse", targetNamespace = "http://validarCPFeCNPJ/", className = "validarcpfecnpj.ValidarCPFeCNPJResponse")
    @Action(input = "http://validarCPFeCNPJ/Validador/validarCPFeCNPJRequest", output = "http://validarCPFeCNPJ/Validador/validarCPFeCNPJResponse")
    public boolean validarCPFeCNPJ(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
